# get question_data : https://opentdb.com/api_config.php
question_data = [{"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"The last Windows operating system to be based on the Windows 9x kernel was Windows 98.","correct_answer":"False","incorrect_answers":["True"]},
                            {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"MacOS is based on Linux.","correct_answer":"False","incorrect_answers":["True"]},
                            {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"It&#039;s not possible to format a write-protected DVD-R Hard Disk.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"Android versions are named in alphabetical order.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.","correct_answer":"False","incorrect_answers":["True"]},
                            {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"The open source program Redis is a relational database server.","correct_answer":"False","incorrect_answers":["True"]},
                            {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.","correct_answer":"True","incorrect_answers":["False"]},
                            {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"&quot;Windows NT&quot; is a monolithic kernel.","correct_answer":"False","incorrect_answers":["True"]},
                            {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.","correct_answer":"False","incorrect_answers":["True"]},
                            {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;","correct_answer":"False","incorrect_answers":["True"]}]